service: aws-lambda

provider:
  name: aws
  runtime: nodejs6.10

functions:
  webhook:
    handler: src/webhook.execute
    events:
      - http:
          path: /webhook
          method: post

plugins:
  - serverless-plugin-typescript
